ateliersoude/event/urls.py
from django.urls import path

from . import views

app_name = "event"


urlpatterns = [
    path(
        "condition/create/<int:orga_pk>/",
        views.ConditionCreateView.as_view(),
        name="condition_create",
    ),
    path(
        "condition/<int:pk>/edit/",
        views.ConditionEditView.as_view(),
        name="condition_edit",
    ),
    path(
        "condition/<int:pk>/delete/",
        views.ConditionDeleteView.as_view(),
        name="condition_delete",
    ),
    path("activity/", views.ActivityListView.as_view(), name="activity_list"),
    path(
        "activity/create/<int:orga_pk>/",
        views.ActivityCreateView.as_view(),
        name="activity_create",
    ),
    path(
        "activity/<int:pk>/edit/",
        views.ActivityEditView.as_view(),
        name="activity_edit",
    ),
    path(
        "activity/<int:pk>/delete/",
        views.ActivityDeleteView.as_view(),
        name="activity_delete",
    ),
    path(
        "activity/<int:pk>/<slug>/",
        views.ActivityView.as_view(),
        name="activity_detail",
    ),
    path("", views.EventListView.as_view(), name="list"),
    path(
        "create/<int:orga_pk>/", views.EventCreateView.as_view(), name="create"
    ),
    path(
        "recurrent/create/<int:orga_pk>/",
        views.RecurrentEventCreateView.as_view(),
        name="recurrent_create",
    ),
    path("<int:pk>/edit/", views.EventEditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.EventDeleteView.as_view(), name="delete"),
    path("<int:pk>/close/", views.CloseEventView.as_view(), name="close"),
    path(
        "<int:pk>/add_active/",
        views.AddActiveEventView.as_view(),
        name="add_active",
    ),
    path(
        "<int:pk>/remove_active/",
        views.RemoveActiveEventView.as_view(),
        name="remove_active",
    ),
    path("<int:pk>/close/", views.CloseEventView.as_view(), name="close"),
    path("<int:pk>/<slug>/", views.EventView.as_view(), name="detail"),
    path(
        "cancel_reservation/<token>/",
        views.CancelReservationView.as_view(),
        name="cancel_reservation",
    ),
    path("book/<token>/", views.BookView.as_view(), name="book"),
    path("absent/<token>/", views.AbsentView.as_view(), name="user_absent"),
]

ateliersoude/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="homepage"),
    path("user/", include("ateliersoude.user.urls", namespace="user")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("event/", include("ateliersoude.event.urls", namespace="event")),
    path(
        "location/",
        include("ateliersoude.location.urls", namespace="location"),
    ),
    path(
        "api/location/",
        include("ateliersoude.location.api_urls", namespace="api_location"),
    ),
    path(r"tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    import debug_toolbar  # noqa

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

ateliersoude/user/urls.py
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [
    path("", views.UserListView.as_view(), name="user_list"),
    path("<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path(
        "update/<int:pk>", views.UserUpdateView.as_view(), name="user_update"
    ),
    path("create/", views.UserCreateView.as_view(), name="user_create"),
    path(
        "create_and_book/",
        views.UserCreateAndBookView.as_view(),
        name="create_and_book",
    ),
    path(
        "organizations/",
        views.OrganizationListView.as_view(),
        name="organization_list",
    ),
    path(
        "organization/create/",
        views.OrganizationCreateView.as_view(),
        name="organization_create",
    ),
    path(
        "organization/<int:pk>/update/",
        views.OrganizationUpdateView.as_view(),
        name="organization_update",
    ),
    path(
        "organization/<int:orga_pk>/<slug>/events/<int:page>/",
        views.OrganizationEventsListView.as_view(),
        name="organization_all_events",
    ),
    path(
        "organization/<int:pk>/<slug>/",
        views.OrganizationDetailView.as_view(),
        name="organization_detail",
    ),
    path(
        "organization/<int:pk>/",
        views.OrganizationDeleteView.as_view(),
        name="organization_delete",
    ),
    path(
        "organization/<int:pk>/add-admin",
        views.AddAdminToOrganization.as_view(),
        name="organization_add_admin",
    ),
    path(
        "organization/<int:pk>/add-active",
        views.AddActiveToOrganization.as_view(),
        name="organization_add_active",
    ),
    path(
        "organization/<int:pk>/add-volunteer",
        views.AddVolunteerToOrganization.as_view(),
        name="organization_add_volunteer",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-actives",
        views.RemoveActiveFromOrganization.as_view(),
        name="remove_from_actives",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-volunteers",
        views.RemoveVolunteerFromOrganization.as_view(),
        name="remove_from_volunteers",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-admins",
        views.RemoveAdminFromOrganization.as_view(),
        name="remove_from_admins",
    ),
    path(
        "present/<int:pk>",
        views.PresentCreateUserView.as_view(),
        name="present_create_user",
    ),
    path(
        "present/<int:event_pk>/<int:pk>/",
        views.PresentMoreInfoView.as_view(),
        name="present_with_more_info",
    ),
    path(
        "organization/<int:pk>/add-member",
        views.AddMemberToOrganization.as_view(),
        name="organization_add_member",
    ),
    path(
        "organization/<int:orga_pk>/update-member/<int:pk>",
        views.UpdateMemberView.as_view(),
        name="organization_update_member",
    ),
]

ateliersoude/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path("", views.UserListView.as_view(), name="user_list"),
    path("userprofile/", views.user_profile, name="user_profile"),
    path("<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("create/", views.register, name="user_create"),
    # Organisation
    path(
        "organization/",
        views.OrganizationListView.as_view(),
        name="organization_list",
    ),
    path(
        "organization/create/",
        views.OrganizationCreateView.as_view(),
        name="organization_create",
    ),
    path(
        "organization/<int:pk>/edit/",
        views.OrganizationEditView.as_view(),
        name="organization_edit",
    ),
    path(
        "organization/<int:pk>/<slug>/",
        views.OrganizationView.as_view(),
        name="organization_detail",
    ),
    path(
        "organization_manager/<int:pk>/",
        views.OrganizationManager,
        name="organization_manager",
    ),
]

ateliersoude/user/views.py
from datetime import date
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
    RedirectView,
)

from ateliersoude import utils
from ateliersoude.event.models import Event
from ateliersoude.event.templatetags.app_filters import tokenize
from ateliersoude.event.views import add_present
from ateliersoude.mixins import (
    HasAdminPermissionMixin,
    HasActivePermissionMixin,
    HasVolunteerPermissionMixin,
)
from ateliersoude.user.mixins import PermissionOrgaContextMixin
from ateliersoude.user.models import CustomUser, Organization, Membership, Fee
from ateliersoude.utils import get_future_published_events

from .forms import (
    UserUpdateForm,
    UserCreateForm,
    OrganizationForm,
    CustomUserEmailForm,
    MoreInfoCustomUserForm,
)

EVENTS_PER_PAGE = 6


class UserUpdateView(UserPassesTestMixin, UpdateView):
    model = CustomUser
    template_name = "user/user_form.html"
    form_class = UserUpdateForm

    def form_valid(self, form):
        res = super().form_valid(form)
        messages.success(self.request, "L'utilisateur a bien été mis à jour.")
        return res

    def test_func(self):
        return self.request.user == self.get_object()


class UserCreateView(CreateView):
    model = CustomUser
    template_name = "user/user_form.html"
    form_class = UserCreateForm
    success_url = reverse_lazy("login")

    def form_valid(self, form):
        res = super().form_valid(form)
        messages.success(self.request, "L'utilisateur a bien été créé")
        return res


class UserCreateAndBookView(CreateView):
    model = CustomUser
    form_class = CustomUserEmailForm
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        self.object = CustomUser.objects.filter(
            email=self.request.POST.get("email", "invalid email")
        ).first()
        if self.object:
            return redirect(self.get_success_url())
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        event_id = self.request.GET.get("event")
        redirect_url = self.request.GET.get("redirect")
        event = get_object_or_404(Event, pk=event_id)
        token = tokenize(self.object, event, "book")
        return (
            reverse("event:book", kwargs={"token": token})
            + f"?redirect={redirect_url}"
        )


class PresentMoreInfoView(UserPassesTestMixin, UpdateView):
    model = CustomUser
    form_class = MoreInfoCustomUserForm
    http_methods = ["post"]

    def form_valid(self, form):
        user = form.save()
        add_present(self.event, user, form.cleaned_data["amount_paid"])
        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        next_url = self.request.GET.get("redirect")
        if utils.is_valid_path(next_url):
            return next_url
        return (
            reverse("event:detail", args=[self.event.id, self.event.slug])
            + "#manage"
        )

    def test_func(self):
        self.event = get_object_or_404(Event, pk=self.kwargs.get("event_pk"))
        return self.request.user in self.event.organization.actives_or_more


class PresentCreateUserView(HasActivePermissionMixin, RedirectView):
    model = Event
    form_class = MoreInfoCustomUserForm
    http_methods = ["post"]

    def get_redirect_url(self, *args, **kwargs):
        event = get_object_or_404(Event, pk=kwargs.get("pk"))
        user = CustomUser.objects.filter(
            email=self.request.POST["email"]
        ).first()
        if user:
            form = MoreInfoCustomUserForm(self.request.POST, instance=user)
        else:
            form = MoreInfoCustomUserForm(self.request.POST)
        user = form.save()
        add_present(event, user, form.cleaned_data["amount_paid"])
        next_url = self.request.GET.get("redirect")
        if utils.is_valid_path(next_url):
            return next_url
        return reverse("event:detail", args=[event.id, event.slug]) + "#manage"


class AddMemberToOrganization(HasActivePermissionMixin, RedirectView):
    model = Organization
    form_class = MoreInfoCustomUserForm
    http_methods = ["post"]

    def get_redirect_url(self, *args, **kwargs):
        user = CustomUser.objects.filter(
            email=self.request.POST["email"]
        ).first()
        url = reverse(
            "user:organization_detail",
            kwargs={
                "pk": self.organization.pk,
                "slug": self.organization.slug,
            },
        )
        if user in self.organization.members.all():
            messages.warning(self.request, "L'utilisateur est déjà membre.")
            return url
        if user:
            form = MoreInfoCustomUserForm(self.request.POST, instance=user)
        else:
            form = MoreInfoCustomUserForm(self.request.POST)
        user = form.save()
        paid = form.cleaned_data["amount_paid"]
        Membership.objects.create(
            organization=self.organization, user=user, amount=paid
        )
        Fee.objects.create(
            amount=paid, user=user, organization=self.organization
        )
        messages.success(self.request, f"Vous avez ajouté {user} avec succes.")
        return url


class UpdateMemberView(HasActivePermissionMixin, UpdateView):
    model = CustomUser
    form_class = MoreInfoCustomUserForm
    http_methods = ["post"]

    def form_valid(self, form):
        user = form.save()
        membership = Membership.objects.get(
            organization=self.organization, user=user
        )
        membership.amount += form.cleaned_data["amount_paid"]
        membership.save()
        Fee.objects.create(
            amount=form.cleaned_data["amount_paid"],
            user=user,
            organization=self.organization,
        )
        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        messages.success(
            self.request, f"Vous avez mis à jour {self.object} avec succes."
        )
        return reverse(
            "user:organization_detail",
            kwargs={
                "pk": self.organization.pk,
                "slug": self.organization.slug,
            },
        )


class UserDetailView(DetailView):
    model = CustomUser
    template_name = "user/user_detail.html"

    def get_object(self, queryset=None):
        custom_user = super().get_object(queryset=queryset)
        user = self.request.user

        if custom_user.is_visible:
            return custom_user

        if user.is_staff:
            return custom_user

        if user.is_authenticated:
            if user.pk == custom_user.pk:
                return custom_user

            organizations = user.active_organizations.all().union(
                user.volunteer_organizations.all(),
                user.admin_organizations.all(),
            )
            can_see_users = CustomUser.objects.filter(
                Q(registered_events__organization__in=list(organizations))
                | Q(presents_events__organization__in=list(organizations))
            )

            if custom_user in can_see_users:
                return custom_user

        raise Http404("Utilisateur introuvable")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = context["object"]
        registered = list(user.registered_events.all())
        context["passed_rendezvous"] = (
            [(event, "present") for event in user.presents_events.all()]
            + [(event, "absent") for event in registered if event.has_ended]
            + [
                (event, "organizer")
                for event in user.organizers_events.all()
                if event.has_ended
            ]
        )
        context["future_rendezvous"] = [
            (event, "") for event in registered if not event.has_ended
        ] + [
            (event, "organizer")
            for event in user.organizers_events.all()
            if not event.has_ended
        ]
        context["passed_rendezvous"].sort(
            key=lambda evt: evt[0].date, reverse=True
        )
        context["future_rendezvous"].sort(key=lambda evt: evt[0].date)
        return context


class UserListView(ListView):
    model = CustomUser
    template_name = "user/user_list.html"
    queryset = CustomUser.objects.filter(is_superuser=False, is_visible=True)


class OrganizationDetailView(PermissionOrgaContextMixin, DetailView):
    model = Organization
    template_name = "user/organization/organization_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["users"] = [
            (f"{user.email} ({user.first_name} {user.last_name})", user.email)
            for user in CustomUser.objects.all()
        ]
        all_events = self.object.events.all()
        context["events"] = list(get_future_published_events(all_events))
        if context["is_volunteer"]:
            context["has_hidden_events"] = all_events.count() > 0
            past_events = all_events.filter(date__lt=date.today()).order_by(
                "date"
            )
            context["page"] = past_events.count() // EVENTS_PER_PAGE + 1
        context["register_form"] = CustomUserEmailForm
        context["add_admin_form"] = CustomUserEmailForm(auto_id="id_admin_%s")
        context["add_active_form"] = CustomUserEmailForm(
            auto_id="id_active_%s"
        )
        context["add_volunteer_form"] = CustomUserEmailForm(
            auto_id="id_volunteer_%s"
        )

ateliersoude/user/templates/user/user_card.html
{% load thumbnail %}

{% for user in users %}
  <div class="card">
    <a class="card-link" href="{{ user.get_absolute_url }}">
      <div class="row text-center" id="square-{{ user.pk }}">
        <div class="col-12">
          {% if user.avatar_img %}
            {% thumbnail user.avatar_img "100x100" crop="center" format="PNG" as im %}
              <img src="{{ im.url }}" class="m-2 rounded-circle"/>
            {% endthumbnail %}
          {% else %}
            <i class="fa fa-user fa-4x m-4 text-primary"></i>
          {% endif %}
        </div>
        <div class="col-12">
          <h5 class="mx-auto col-12">
              {{ user.first_name|capfirst }} {{ user.last_name|capfirst}}
          </h5>
        </div>
      </div>
    </a>
    <ul class="list-group list-group-flush">
      {% if user.member_organizations.all %}
        <li class="list-group-item">
          <small> 
          <i>
            est membre de : 
            {{ user.member_organizations.all|join:", " }}
          </i>
          </small>
        </li>
      {% endif %}
      {% if user.active_organizations.all %}
        <li class="list-group-item">
          <small> 
          <i>
            est volontaire de :
            {{ user.active_organizations.all|join:", " }}
            {% if user.active_organizations.all and user.volunteer_organizations.all %}, {% endif %}
            {{ user.volunteer_organizations.all|join:", " }}
          </i>
          </small>
        </li>
      {% endif %}
      {% if user.admin_organizations.all %}
        <li class="list-group-item">
          <small> 
          <i>
            est administrateur de : 
            {{ user.admin_organizations.all|join:", " }}
          </i>
          </small>
        </li>
      {% endif %}
    </ul>
  </div>
{% empty %}
  <div>No users yet.</div>  
{% endfor %}

ateliersoude/user/templates/user/user_detail.html
{% extends 'base.html' %}
{% load assets %}

{% load app_filters %}
{% load thumbnail %}

{% block extra_css %}
  {% assets "css_detail_user" %}
    <link type="text/css" href="{{ ASSET_URL }}" rel="stylesheet"/>
  {% endassets %}
{% endblock %}

{% block content %}
  {% url "user:user_list" as user_list_url %}
  {% include "breadcrumb.html" with current=object first_parent_url=user_list_url first_parent_text="Communauté" %}

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1>{{ object }}</h1>
      {% if request.user.pk == object.pk and not object.first_name or not object.last_name or not object.street_address %}
        <div class="alert alert-warning" role="alert">
          Pour devenir membre d'une organisation, vous devez renseigner votre Nom, Prénom
          et Adresse postale.
        </div>
      {% endif %}
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-md-10">
        <div class="row">
          <ul class="list-group">
            {% for organization in object.visitor_organizations.all %}
              <li class="list-group-item">
                Visiteur
                <a href="{% url 'user:organization_detail' organization.pk organization.slug %}">
                  {{ organization.name }}
                </a>
              </li>
            {% endfor %}
            {% for organization in object.member_organizations.all %}
              <li class="list-group-item">
                Membre
                <a href="{% url 'user:organization_detail' organization.pk organization.slug %}">
                  {{ organization.name }}
                </a>
              </li>
            {% endfor %}
            {% for organization in object.active_organizations.all %}
              <li class="list-group-item">
                Membre volontaire
                <a href="{% url 'user:organization_detail' organization.pk organization.slug %}">
                  {{ organization.name }}
                </a>
              </li>
            {% endfor %}
            {% for organization in object.admin_organizations.all %}
              <li class="list-group-item">
                Administrateur à
                <a href="{% url 'user:organization_detail' organization.pk organization.slug %}">
                  {{ organization.name }}
                </a>
              </li>
            {% endfor %}

            {% if not object.get_organizations %}
              <p>Ce profil n'est rattaché à aucune organisation</p>
            {% endif %}
          </ul>
        </div>
        {% if object.pk == request.user.pk %}
          <div class="row">
            <a class="mr-3 btn btn-primary" href="{% url "user:user_update" object.pk %}">
              <i class="fa fa-pencil-square-o 2-xs pt-1"></i>
              Editer mon profil
            </a>
            <a class="btn btn-warning" href="{% url "logout" %}">Deconnexion</a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>



  <section class="container">
  <div class="row justify-content-md-center">
  <section class="col-md-6">

    <div class="card">
      <div class="card-header text-center">
        <div class="col-lg">
          {% if object.avatar_img %}
            {% thumbnail object.avatar_img "100x100" crop="center" format="PNG" as im %}
              <img src="{{ im.url }}" class="m-2 rounded-circle"/>
            {% endthumbnail %}
          {% else %}
            <i class="fa fa-user fa-4x m-4 text-primary"></i>
          {% endif %}
        </div>
        <h5 class="mx-auto col-12">
          {{ object.first_name|capfirst }} {{ object.last_name|capfirst}}
        </h5>
      </div>
      <div class="card-body">
        <ul class="list-group">
          <li class="list-group-item">
            <i class="fa fa-phone pr-2"></i>{{ object.phone_number }}
          </li>
          <li class="list-group-item">
            <i class="fa fa-envelope pr-2"></i>{{ object.email }}
          </li>
          <li class="list-group-item">
            <i class="fa fa-map pr-2"></i>{{ object.street_address }}
          </li>
          <li class="list-group-item">
            <i class="fa fa-birthday-cake pr-2"></i>{{ object.birth_date }}
          </li>
          <li class="list-group-item">
            <i class="fa fa-clock pr-2"></i> Membre depuis le {{ object.date_joined|date:"d F Y" }}
          </li>
        </ul>
      </div>
    </div>

  </section>

  {% if passed_rendezvous or future_rendezvous %}

    <section class="col-md-6">
      {% if future_rendezvous %}
        <h5 class="border-bottom border-gray pb-2">Rendez-vous à venir</h5>
        <div class="row scrollable">
          <ul class="list-group w-100">
            {% for event, status in future_rendezvous %}
              <li class="list-group-item">
                <a href="{% url 'event:detail' event.pk event.slug %}">
                  {{ event.activity.name }} {{ event.date|date:"d F Y" }}
                </a>
                {% if status == "organizer" %}
                <span class="badge badge-pill badge-success">Orga</span>
                {% else %}
                  {% if object.pk == request.user.pk %}
                    {% tokenize user=object event=event action='cancel' as tok %}
                    <a class="btn btn-error" href="{% url 'event:cancel_reservation' tok %}">
                      Annuler ma présence
                    </a>
                  {% endif %}
                {% endif %}
              </li>
            {% endfor %}
          </ul>
        </div>
        <hr>
      {% endif %}

      <h5 class="border-bottom border-gray pb-2">Rendez-vous passés</h5>
      <div class="row scrollable">
        <ul class="list-group w-100">
          {% for event, status in passed_rendezvous %}
            <li class="list-group-item">
              {% if status == "organizer" %}
                <a href="{% url 'event:detail' event.pk event.slug %}">
                  {{ event.activity.name }} {{ event.date|date:"d F Y" }}
                </a>
                <span class="badge badge-pill badge-success">Orga</span>
              {% elif status == "absent" %}
                {{ event.activity.name }} {{ event.date|date:"d F Y" }}
                <span class="badge badge-pill badge-secondary">Absent</span>
              {% elif status == "present" %}
                {{ event.activity.name }} {{ event.date|date:"d F Y" }}
                <span class="badge badge-pill badge-info">A participé</span>
              {% endif %}
            </li>
          {% endfor %}
        </ul>
      </div>
    </section>

  {% endif %}


{% endblock %}

ateliersoude/user/templates/user/user_form.html
{% extends 'base.html' %}
{% load bootstrap4 assets %}

{% block extra_css %}
  {% assets "css_autocomplete" %}
    <link type="text/css" href="{{ ASSET_URL }}" rel="stylesheet"/>
  {% endassets %}
{% endblock %}

{% block content %}
  {% url "user:user_list" as user_list_url %}
  {% if object %}
    {% url "user:user_detail" object.pk as user_detail_url %}
    {% include "breadcrumb.html" with current="Mise à jour" second_parent_url=user_detail_url second_parent_text="Communauté" first_parent_url=user_detail_url first_parent_text=object %}
  {% else %}
    {% include "breadcrumb.html" with current="Création" first_parent_url=user_list_url first_parent_text="Communauté" %}
  {% endif %}

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1>Mes informations</h1>
    </div>
  </div>

  <div class="container">
    <div class="card p-3">
      <form method="post" enctype="multipart/form-data">
        <fieldset>
          {% csrf_token %}
          {% bootstrap_form form %}
          <button type="submit" class="btn btn-primary">Enregistrer</button>
        </fieldset>
      </form>
    </div>
  </div>
{% endblock %}

{% block extra_js %}
  {{ form.media }}
  {% assets "js_create_edit_user" %}
    <script src="{{ ASSET_URL }}"></script>
  {% endassets %}
{% endblock %}

ateliersoude/user/templates/user/user_list.html
{% extends 'base.html' %}

{% block content %}
  {% include "breadcrumb.html" with current="Communauté" %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1>Utilisateurs</h1>
  </div>
</div>

<section class="container">
  <div class="row col-md-12">
    <div class="card-columns">
      {% include 'user/user_card.html' with users=object_list %}
    </div>
  </div>
</section>

{% endblock %}